#include "warnbar.hpp"

#include <cstdio>
#include <cstdlib>
#include <string>

static int failures = 0;

#define CHECK(cond)                                                            \
    do {                                                                       \
        if (!(cond)) {                                                         \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);        \
            ++failures;                                                        \
        }                                                                      \
    } while (0)

int main() {
    // Strip height is a sane visible-but-small value.
    CHECK(aquawm::WARN_BAR_HEIGHT >= 16 && aquawm::WARN_BAR_HEIGHT <= 64);

    // Message names the config path and the kill switch.
    {
        std::string m = aquawm::warn_bar_message("/home/u/.config/aquawm/aquawm.lua");
        CHECK(m.find("/home/u/.config/aquawm/aquawm.lua") != std::string::npos);
        CHECK(m.find("autogenerated_warn") != std::string::npos);
        CHECK(m.find("false") != std::string::npos);
    }

    // Centering: text narrower than the image centers, overlong clamps left.
    CHECK(aquawm::warn_text_x(1920, 1000) == 460);
    CHECK(aquawm::warn_text_x(1920, 1920) == 0);
    CHECK(aquawm::warn_text_x(800, 1000) == 0);
    CHECK(aquawm::warn_text_x(1920, 0) == 960);

    if (failures == 0) {
        std::puts("test_warnbar: all checks passed");
        return 0;
    }
    std::printf("test_warnbar: %d check(s) failed\n", failures);
    return 1;
}
