#include "config.hpp"

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;

static int failures = 0;

#define CHECK(cond)                                                            \
    do {                                                                       \
        if (!(cond)) {                                                         \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);        \
            ++failures;                                                        \
        }                                                                      \
    } while (0)

int main() {
    using aquawm::Config;

    // Pin the environment: path resolution reads XDG_CONFIG_HOME first.
    const char *saved_xdg = std::getenv("XDG_CONFIG_HOME");
    unsetenv("XDG_CONFIG_HOME");

    // Compiled-in defaults mirror the original hardcoded behavior.
    {
        Config c = aquawm::default_config();
        CHECK(c.gaps == 0);
        CHECK(c.mfact > 0.54f && c.mfact < 0.56f);
        CHECK(c.nmaster == 1);
        CHECK(c.workspaces == 4);
        CHECK(c.wallpaper.ends_with("aquawm/wallpaper.jpg"));
        CHECK(c.layout == "master");
        CHECK(c.terminal == "kitty");
        CHECK(c.split_ratio > 0.49f && c.split_ratio < 0.51f);
        CHECK(c.autogenerated_warn == true);
        bool has_quit = false, has_ws = false;
        for (const auto &k : c.keys) {
            has_quit = has_quit || k.action == "quit";
            has_ws = has_ws || k.action == "workspace";
        }
        CHECK(has_quit && has_ws);
    }

    // Legacy fallback: old tilewm paths are honored when aquawm ones
    // do not exist, so renaming never strands an existing setup.
    {
        const char *old_home = std::getenv("HOME");
        fs::path sandbox = fs::temp_directory_path() / "aquawm-fallback-test";
        fs::remove_all(sandbox);
        fs::create_directories(sandbox / ".config" / "tilewm");
        {
            std::ofstream f(sandbox / ".config" / "tilewm" / "init.lua");
            f << "config = { gaps = 5 }\n";
        }
        setenv("HOME", sandbox.c_str(), 1);
        // Only the legacy file exists: it wins, with default wallpaper
        // falling back to the legacy image if present.
        CHECK(aquawm::resolve_config_path("") ==
              (sandbox / ".config" / "tilewm" / "init.lua").string());
        CHECK(aquawm::resolve_wallpaper_path("") ==
              (sandbox / ".config" / "aquawm" / "wallpaper.jpg").string());
        fs::create_directories(sandbox / ".config" / "aquawm");
        {
            std::ofstream f(sandbox / ".config" / "aquawm" / "aquawm.lua");
            f << "config = { gaps = 7 }\n";
        }
        // New location wins once it exists.
        CHECK(aquawm::resolve_config_path("") ==
              (sandbox / ".config" / "aquawm" / "aquawm.lua").string());
        // Explicit paths always win untouched.
        CHECK(aquawm::resolve_config_path("/tmp/x.lua") == "/tmp/x.lua");
        // Wallpaper: the built-in default means "no choice", so a legacy
        // image is preferred over a missing default; explicit paths win.
        CHECK(aquawm::resolve_wallpaper_path(aquawm::default_wallpaper_path()) ==
              (sandbox / ".config" / "aquawm" / "wallpaper.jpg").string());
        {
            std::ofstream img(sandbox / ".config" / "tilewm" / "wallpaper.jpg");
            img << "fakejpeg";
        }
        CHECK(aquawm::resolve_wallpaper_path(aquawm::default_wallpaper_path()) ==
              (sandbox / ".config" / "tilewm" / "wallpaper.jpg").string());
        CHECK(aquawm::resolve_wallpaper_path("/tmp/custom.jpg") == "/tmp/custom.jpg");
        if (old_home != nullptr) {
            setenv("HOME", old_home, 1);
        }
        fs::remove_all(sandbox);
    }

    // Modifier parsing.
    {
        bool ok = false;
        CHECK(aquawm::parse_mods("Alt+Shift", ok) ==
              (aquawm::MOD_ALT | aquawm::MOD_SHIFT));
        CHECK(ok);
        CHECK(aquawm::parse_mods("ctrl+alt", ok) ==
              (aquawm::MOD_CTRL | aquawm::MOD_ALT));
        CHECK(ok);
        CHECK(aquawm::parse_mods("Super", ok) == aquawm::MOD_SUPER);
        CHECK(ok);
        aquawm::parse_mods("Alt+Frobnicator", ok);
        CHECK(!ok);
    }

    // Actions.
    CHECK(aquawm::known_action("reload-config"));
    CHECK(!aquawm::known_action("make-coffee"));

    // Missing file is an error, config untouched.
    {
        Config c = aquawm::default_config();
        std::string err;
        CHECK(!aquawm::load_config_file("/nonexistent-aquawm-init.lua", c, err));
        CHECK(!err.empty());
        CHECK(c.gaps == 0 && c.keys.size() == aquawm::default_config().keys.size());
    }

    // A real file overrides values and replaces binds.
    {
        const char *path = "/tmp/aquawm-test-init.lua";
        {
            std::ofstream f(path);
            f << "config = { gaps = 12, mfact = 0.7, nmaster = 2, workspaces = 2,\n"
                  "  wallpaper = \"/tmp/wall.jpg\" }\n"
                  "bind(\"Alt\", \"x\", \"close\")\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path, c, err));
        CHECK(c.gaps == 12);
        CHECK(c.mfact > 0.69f && c.mfact < 0.71f);
        CHECK(c.nmaster == 2);
        CHECK(c.workspaces == 2);
        CHECK(c.wallpaper == "/tmp/wall.jpg");
        CHECK(c.keys.size() == 1 && c.keys[0].action == "close");
        std::remove(path);
    }

    // A file with no binds keeps the previous keymap.
    {
        const char *path = "/tmp/aquawm-test-init2.lua";
        {
            std::ofstream f(path);
            f << "config = { gaps = 3 }\n";
        }
        Config c = aquawm::default_config();
        const std::size_t nkeys = c.keys.size();
        std::string err;
        CHECK(aquawm::load_config_file(path, c, err));
        CHECK(c.gaps == 3 && c.keys.size() == nkeys);
        std::remove(path);
    }

    // VRR, keyboard and output modes parse; vrr clamps to 0..2.
    {
        const char *path = "/tmp/aquawm-test-init-p6.lua";
        {
            std::ofstream f(path);
            f << "config = { vrr = 9,\n"
                  "  keyboard = { layout = \"us,hu\", options = \"grp:alt_shift_toggle\" },\n"
                  "  outputs = { { name = \"DP-1\", width = 2560, height = 1440, refresh = 144 } } }\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path, c, err));
        CHECK(c.vrr == 2);
        CHECK(c.keyboard.layout == "us,hu");
        CHECK(c.keyboard.options == "grp:alt_shift_toggle");
        CHECK(c.keyboard.variant.empty());
        CHECK(c.outputs.size() == 1);
        CHECK(c.outputs[0].name == "DP-1");
        CHECK(c.outputs[0].width == 2560 && c.outputs[0].height == 1440);
        CHECK(c.outputs[0].refresh > 143.9f && c.outputs[0].refresh < 144.1f);
        std::remove(path);
    }

    // A missing keyboard/outputs section keeps previous values.
    {
        const char *path = "/tmp/aquawm-test-init-p6b.lua";
        {
            std::ofstream f(path);
            f << "config = { gaps = 5 }\n";
        }
        Config c = aquawm::default_config();
        c.vrr = 1;
        c.keyboard.layout = "hu";
        std::string err;
        CHECK(aquawm::load_config_file(path, c, err));
        CHECK(c.vrr == 1 && c.keyboard.layout == "hu" && c.outputs.empty());
        std::remove(path);
    }

    // Broken Lua and bad binds are errors.
    {
        const char *path = "/tmp/aquawm-test-init3.lua";
        {
            std::ofstream f(path);
            f << "bind(\"Alt\", \"not-a-real-key-xyz\", \"close\")\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(!aquawm::load_config_file(path, c, err));
        CHECK(!err.empty());
        std::remove(path);
    }

    // XDG_CONFIG_HOME override: absolute paths win, relative ones are
    // ignored per spec, and the warning-bar kill switch parses.
    {
        fs::path sandbox = fs::temp_directory_path() / "aquawm-xdg-test";
        fs::remove_all(sandbox);
        fs::create_directories(sandbox / "custom");
        setenv("XDG_CONFIG_HOME", (sandbox / "custom").c_str(), 1);
        CHECK(aquawm::default_config_path() ==
              (sandbox / "custom" / "aquawm" / "aquawm.lua").string());
        CHECK(aquawm::default_wallpaper_path() ==
              (sandbox / "custom" / "aquawm" / "wallpaper.jpg").string());
        setenv("XDG_CONFIG_HOME", "relative/path", 1);
        const char *home = std::getenv("HOME");
        std::string base =
            (home != nullptr && home[0] != '\0') ? home : "/tmp";
        CHECK(aquawm::default_config_path() ==
              base + "/.config/aquawm/aquawm.lua");
        unsetenv("XDG_CONFIG_HOME");
        fs::remove_all(sandbox);
    }

    // autogenerated_warn parses (default true, explicit false sticks).
    {
        CHECK(aquawm::default_config().autogenerated_warn == true);
        fs::path path =
            fs::temp_directory_path() / "aquawm-warn-test.lua";
        {
            std::ofstream f(path);
            f << "config = { autogenerated_warn = false }\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path.c_str(), c, err));
        CHECK(c.autogenerated_warn == false);
        std::remove(path.c_str());
    }

    // terminal + layout parse (defaults stick when absent).
    {
        fs::path path =
            fs::temp_directory_path() / "aquawm-layout-test.lua";
        {
            std::ofstream f(path);
            f << "config = { layout = \"dwindle\", split_ratio = 0.3, terminal = \"foot\" }\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path.c_str(), c, err));
        CHECK(c.layout == "dwindle");
        CHECK(c.split_ratio > 0.29f && c.split_ratio < 0.31f);
        CHECK(c.terminal == "foot");
        std::remove(path.c_str());
    }

    // Unknown layout names fall back to master.
    {
        fs::path path =
            fs::temp_directory_path() / "aquawm-badlayout-test.lua";
        {
            std::ofstream f(path);
            f << "config = { layout = \"nope\" }\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path.c_str(), c, err));
        CHECK(c.layout == "master");
        std::remove(path.c_str());
    }

    // rule() parses match/effects; errors fail the load loudly.
    {
        fs::path path =
            fs::temp_directory_path() / "aquawm-rules-test.lua";
        {
            std::ofstream f(path);
            f << "rule({ match = { app_id = \"firefox\" }, workspace = 2 })\n"
              << "rule({ match = { xwayland = true }, float = true })\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(aquawm::load_config_file(path.c_str(), c, err));
        CHECK(c.rules.size() == 2);
        CHECK(c.rules[0].match.app_id == "firefox");
        CHECK(!c.rules[0].floating.has_value());
        CHECK(c.rules[0].workspace == 2);
        CHECK(c.rules[1].match.xwayland.has_value());
        CHECK(c.rules[1].match.xwayland.value() == true);
        CHECK(c.rules[1].floating.has_value());
        CHECK(c.rules[1].floating.value() == true);
        std::remove(path.c_str());
    }

    // Bad rules fail loudly: wrong field types, bad workspace.
    {
        fs::path path =
            fs::temp_directory_path() / "aquawm-badrules-test.lua";
        {
            std::ofstream f(path);
            f << "rule({ match = { app_id = 42 }, float = true })\n";
        }
        Config c = aquawm::default_config();
        std::string err;
        CHECK(!aquawm::load_config_file(path.c_str(), c, err));
        CHECK(!err.empty());
        std::remove(path.c_str());
    }

    if (saved_xdg != nullptr) {
        setenv("XDG_CONFIG_HOME", saved_xdg, 1);
    }

    if (failures == 0) {
        std::puts("test_config: all checks passed");
        return 0;
    }
    std::printf("test_config: %d check(s) failed\n", failures);
    return 1;
}
