-- aquawm example config: copy to ~/.config/aquawm/aquawm.lua and tweak.
-- Reload a running compositor with Super+Shift+R (or SIGHUP).
-- Key names follow xkb keysyms ("Return", "space", "q", "1" ...).
-- Modifiers: Alt, Ctrl, Shift, Super (Logo/Win/Mod4 also work).

config = {
    gaps = 8,      -- pixels around each window and the screen edge
    mfact = 0.60,  -- master column width fraction (0.05 .. 0.95)
    nmaster = 1,   -- windows in the master column
    workspaces = 4, -- number of workspaces (1 .. 9)
    autogenerated_warn = true, -- fallback-config warning bar; false hides it
    -- wallpaper = os.getenv("HOME") .. "/.config/aquawm/wallpaper.jpg",
}

bind("Super", "Return", "spawn-terminal")
bind("Super", "j", "focus-next")
bind("Super", "k", "focus-prev")
bind("Super", "t", "toggle-floating")
bind("Super", "q", "close")
bind("Super", "m", "quit") -- back to the login manager (the only quit bind)
bind("Super+Shift", "r", "reload-config")

for i = 1, 4 do
    bind("Super", tostring(i), "workspace", i)
    bind("Super+Shift", tostring(i), "move-to-workspace", i)
end
