-- aquawm example config: copy to ~/.config/aquawm/aquawm.lua and tweak.
-- Saving this file reloads it automatically; Super+Shift+R (or SIGHUP)
-- reloads manually.
-- Key names follow xkb keysyms ("Return", "space", "q", "1" ...).
-- Modifiers: Alt, Ctrl, Shift, Super (Logo/Win/Mod4 also work).

config = {
    gaps = 8,      -- pixels around each window and the screen edge
    mfact = 0.60,  -- master column width fraction (0.05 .. 0.95)
    nmaster = 1,   -- windows in the master column
    workspaces = 4, -- number of workspaces (1 .. 9)
    autogenerated_warn = true, -- fallback-config warning bar; false hides it
    layout = "master", -- tiling layout: master, dwindle, grid, monocle
    split_ratio = 0.50, -- dwindle split fraction (0.10 .. 0.90)
    terminal = "kitty", -- spawned on Super+Return
    -- wallpaper = os.getenv("HOME") .. "/.config/aquawm/wallpaper.jpg",
    -- Outputs, VRR and keyboard (all live-applied on save):
    -- outputs: fixed mode per connector; omitted fields keep preferred.
    -- outputs = {
    --     { name = "DP-1", width = 2560, height = 1440, refresh = 144 },
    -- },
    vrr = 0, -- adaptive sync: 0 off, 1 windowed+fullscreen, 2 fullscreen-only
    -- keyboard: xkb layouts; "us,hu" + grp toggle = runtime language switch.
    keyboard = { layout = "us", variant = "", options = "" },
}

bind("Super", "Return", "spawn-terminal")
bind("Super", "j", "focus-next")
bind("Super", "k", "focus-prev")
bind("Super", "t", "toggle-floating")
bind("Super", "q", "close")
bind("Super", "m", "quit") -- back to the login manager (the only quit bind)
bind("Super", "l", "cycle-layout") -- master -> dwindle -> grid -> monocle
bind("Super+Shift", "r", "reload-config")

for i = 1, 4 do
    bind("Super", tostring(i), "workspace", i)
    bind("Super+Shift", tostring(i), "move-to-workspace", i)
end

-- Window rules: evaluated top to bottom when a window maps, later
-- matches win. Substring match; xwayland matches X11 clients.
-- rule({ match = { app_id = "firefox" }, workspace = 2 })
-- rule({ match = { title = "Picture-in-Picture" }, float = true })
-- rule({ match = { xwayland = true }, float = true })
