#pragma once

// aquawm configuration model: plain C++ values, no Lua types here, so this
// header stays includable and unit-testable anywhere. config.cpp bridges
// these to an init.lua file; main.cpp consumes them.

#include <cstdint>
#include <string>
#include <vector>

#include "rules.hpp"

namespace aquawm {

// Modifier bits for Keybind::mods (mapped to WLR_MODIFIER_* by main.cpp).
constexpr uint32_t MOD_SHIFT = 1u << 0;
constexpr uint32_t MOD_CTRL = 1u << 1;
constexpr uint32_t MOD_ALT = 1u << 2;
constexpr uint32_t MOD_SUPER = 1u << 3;

struct Keybind {
    uint32_t mods = 0;
    uint32_t keysym = 0; // xkb keysym
    std::string action;
    int arg = 0; // 1-based workspace number for workspace actions
};

// Fixed output mode from Lua: matched by connector name ("DP-1").
// Zero width/height keeps the preferred mode; zero refresh keeps the
// preferred rate. Refresh is in Hz (converted to mHz for wlroots).
struct OutputMode {
    std::string name; // empty matches any output (first match wins)
    int width = 0;
    int height = 0;
    float refresh = 0;
};

// xkb rule names for every keyboard: layout = "us,hu" with
// options = "grp:alt_shift_toggle" gives runtime language switching.
struct KeyboardConfig {
    std::string layout;
    std::string variant;
    std::string options;
};

struct Config {
    int gaps = 0;        // pixels around each window (and screen edge)
    float mfact = 0.55f; // master column width fraction
    int nmaster = 1;     // windows in the master column
    int workspaces = 4;  // number of workspaces (1..9)
    std::string wallpaper; // background image path (empty = default path)
    bool autogenerated_warn = true; // show fallback-config warning bar
    std::string layout = "master"; // tiling layout, see tiling.hpp
    float split_ratio = 0.5f; // dwindle split fraction
    std::string terminal = "kitty"; // spawned on Super+Return
    int vrr = 0; // adaptive sync: 0 off, 1 always, 2 fullscreen-only
    KeyboardConfig keyboard; // xkb layout/variant/options, empty = default
    std::vector<OutputMode> outputs; // fixed modes by connector name
    std::vector<Keybind> keys;
    std::vector<Rule> rules; // evaluated at map time, in file order
};

// Layout names arrange() understands, in cycle order.
inline const std::vector<std::string> &layout_names() {
    static const std::vector<std::string> names{
        "master", "dwindle", "grid", "monocle"};
    return names;
}

inline bool known_layout(const std::string &name) {
    for (const auto &n : layout_names()) {
        if (n == name) {
            return true;
        }
    }
    return false;
}

// Built-in defaults mirroring the original hardcoded behavior.
Config default_config();

// Parse "Alt+Shift" style specs (separators + - |, case-insensitive).
// Tokens: shift, ctrl, alt, super/logo/win/mod4. ok=false on unknown token.
uint32_t parse_mods(const std::string &spec, bool &ok);

// All action names run_action() understands.
bool known_action(const std::string &action);

// Load path (an init.lua file) into out. Returns false with a message in
// error on any failure; out is left at its incoming value on failure.
bool load_config_file(const char *path, Config &out, std::string &error);

// $HOME/.config/aquawm/aquawm.lua (falls back to /root/... for UID 0, which
// is why the compositor should run as a normal user).
std::string default_config_path();

// The pre-rename location, honored once with a warning when the new one
// does not exist, so existing setups keep working after the rename.
std::string legacy_config_path();

// Default wallpaper location next to the config file. An empty wallpaper
// field in Config resolves to this.
std::string default_wallpaper_path();

// Resolve which config file to load: explicit path wins, otherwise the
// default, otherwise the legacy location. Never fails; missing files are
// reported by load_config_file with built-in defaults as fallback.
std::string resolve_config_path(const std::string &explicit_path);

// Resolve the wallpaper image: explicit setting wins, otherwise the
// default, otherwise the legacy location. May point at a missing file;
// the caller logs and degrades gracefully in that case.
std::string resolve_wallpaper_path(const std::string &configured);

} // namespace aquawm
