#pragma once

// Fallback-config warning bar (Phase 3c+): pure logic, no wlroots or
// freetype types here, so this header stays unit-testable anywhere.
//
// When the compositor runs on built-in defaults (missing/broken config),
// it shows a strip at the top of every output telling the user where the
// config lives and how to hide the strip. The strip reserves space so
// tiling never covers it.

#include <string>

namespace aquawm {

// Strip height in output pixels; amber background, black text.
constexpr int WARN_BAR_HEIGHT = 26;

// The on-screen message. Points at the config file and names the kill
// switch, so the bar is self-explanatory without documentation.
inline std::string warn_bar_message(const std::string &config_path) {
    return "AquaWM: using built-in defaults - edit " + config_path +
           " to configure (set autogenerated_warn = false to hide this bar)";
}

// X offset that centers text of pixel width text_w in an image of width
// img_w. Clamps at zero so overlong text starts at the left edge instead
// of running off both sides.
inline int warn_text_x(int img_w, int text_w) {
    const int x = (img_w - text_w) / 2;
    return x < 0 ? 0 : x;
}

} // namespace aquawm
